version: '3.8'

services:
  # データベース (PostgreSQL)
  db:
    image: postgres:15-alpine
    container_name: anime_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d # dbフォルダにあるテーブル設計を適用

#   # データベース管理ツール (PgAdmin) - オプションですがあると便利です
#   pgadmin:
#     image: dpage/pgadmin4
#     container_name: anime_pgadmin
#     ports:
#       - "8080:80"
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@example.com}
#       PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#     depends_on:
#       - db

# volumes:
#   postgres_data: